# Useful Packages

1. [**math**](https://docs.python.org/3/library/math.html) - Provides mathematical functions and constants for numerical computations.
2. [**datetime**](https://docs.python.org/3/library/datetime.html) - Supplies classes for manipulating dates and times in both simple and complex ways.
3. [**itertools**](https://docs.python.org/3/library/itertools.html) - Creates iterators for efficient looping and combinatorial operations.
4. [**more_itertools**](https://more-itertools.readthedocs.io/) - Extended toolkit for creating and using iterators, building on itertools.
5. [**numpy**](https://numpy.org/doc/stable/) - Fundamental package for numerical computing with support for large, multi-dimensional arrays and matrices.
6. [**pandas**](https://pandas.pydata.org/docs/) - Data analysis and manipulation library providing DataFrames and Series for working with structured data.
7. [**polars**](https://docs.pola.rs/) - High-performance DataFrame library written in Rust with Python bindings, designed for fast data processing.
8. [**plotly**](https://plotly.com/python/) - Interactive visualization library for creating web-based, interactive charts and dashboards.
9. [**matplotlib**](https://matplotlib.org/stable/contents.html) - Comprehensive plotting library for creating static, animated, and interactive visualizations.
10. [**control**](https://python-control.readthedocs.io/) - Python Control System Library for analyzing and designing control systems.

## Other useful packages

11. [**networkx**](https://networkx.org/documentation/stable/) - Python package for creating, manipulating, and analyzing complex networks and graphs.
12. [**panel**](https://panel.holoviz.org/) - High-level app and dashboarding solution from HoloViz for building interactive web applications.
13. [**pandapower**](https://pandapower.readthedocs.io/) - Open-source power systems analysis and simulation library based on pandas.
14. [**pyomo**](https://pyomo.readthedocs.io/) - Python-based open-source optimization modeling language for linear, nonlinear, and mixed-integer programming.
15. [**Shapely**](https://shapely.readthedocs.io/) - Package for working with geometric objects and performing spatial operations. It helps you create, manipulate, and analyze shapes like points, lines, and polygons.
16. [**DuckDB**](https://duckdb.org/docs/) - A fast, lightweight analytical database designed for local and in-process data processing. It’s ideal for running SQL queries efficiently on large datasets without needing a separate server.

# Python Tips

- Use Jupyter Notebooks for exploring ideas and implementing code. Once the code is ready, move it into a function or class in a separate Python file so your main `.py` or `.ipynb` file stays small and clear.
- It is often better to have many small files than one large, monolithic file.
- Keep functional code in the `src` folder, and place tests, experiments, and visualizations in separate folders.
- When using GitHub, commit regularly with clear commit messages.
- Import every package at the beginning of files
- Avoid using magic numbers or hardcoded values directly in the implementation logic. Instead, declare them as named constants at the top of the file.
- Writing conventions:
  - Constants in **UPPERCASE**
  - Variables, functions, and objects in **snake_case**
  - Classes in **CamelCase**

In [1]:
CONSTANT_VALUE = 52

def my_new_function():
    pass

class MyNewClass:
    pass

Python is an untyped programming language. However, in large projects, you should consider using type hints to help ensure your code is correct and easier to maintain.

In [ ]:
my_float: float = 3.14

# Coding tips
# 0 Package importation

In [1]:
import datetime
from datetime import datetime as dt

print(datetime.datetime(2015, 1, 1))
print(dt(2015, 1, 1))
print(dt.now())

2015-01-01 00:00:00
2015-01-01 00:00:00
2026-09-03 09:12:20.544610



# 1 Deep Copy vs Shallow Copy

## Overview

When working with objects and data structures in programming, understanding the difference between shallow copy and deep copy is crucial. These concepts define how data is duplicated when you copy a variable or object.

### Shallow Copy

A shallow copy creates a new object, but does not recursively copy nested objects. Instead, it only copies the references to the nested objects. This means the original and the copy share the same nested objects in memory.

#### Characteristics

- Creates a new container/object
- Copies only the references to nested objects, not the objects themselves
- Changes to nested objects affect both the original and the copy
- Faster and uses less memory than deep copy
- Only goes "one level deep"

Use Shallow Copy When:

- You're only modifying top-level properties/elements
- You need better performance and lower memory usage
- You want to share nested object references intentionally
- Working with immutable nested objects

### Deep Copy

A deep copy creates a completely independent copy of an object and all nested objects within it. The original and the copy do not share any references in memory at any level of nesting.

#### Characteristics

- Creates a new container or object at the top level
- Recursively copies all nested objects, arrays, and data structures
- Changes to any level of nesting only affect the copy, not the original
- Slower and uses more memory than shallow copy
- Complete independence between original and copy at all levels
- Ensures total data isolation0

#### Use Deep Copy When:

- You need complete independence from the original
- You'll be modifying nested objects
- You're working with complex nested structures
- Data integrity is critical

In [4]:
from copy import deepcopy
# Original list containing a nested list
original_list = [[1, 2, 3], [4, 5, 6]]

# 1. Create a shallow copy
shallow_copied_list = original_list

# 2. Create a deep copy
deep_copied_list = deepcopy(original_list)

# Modify a nested element in the shallow copy
shallow_copied_list[0][0] = 99



print("Original:", original_list)
print("Shallow Copy:", shallow_copied_list)
print("Deep Copy:", deep_copied_list)

# 3. copy an element from the original list to the deep copy
element_copy = original_list[1][1]

print("\nElement_copy:", element_copy)
element_copy = 27

print("Modified element_copy:", element_copy)
print("Original after modifying element copy:", original_list[1][1])

Original: [[99, 2, 3], [4, 5, 6]]
Shallow Copy: [[99, 2, 3], [4, 5, 6]]
Deep Copy: [[1, 2, 3], [4, 5, 6]]

Element_copy: 5
Modified element_copy: 27
Original after modifying element copy: 5

# 2 For loop

## 2.1 zip() - Combining multiple iterables, creating dictionaries, transposing matrice
- Can combine different iterable types
- Always take the smallest lenght of the iterables

In [5]:

names = ["Alice", "Bob", "Charlie"]
ages = [25, 30, 35]


for name, age in zip(names, ages):
    print(f"{name} is {age} years old")

Alice is 25 years old
Bob is 30 years old
Charlie is 35 years old

In [8]:

print("\nDifferent size")

list1 = [1, 2, 3, 4, 5]
list2 = ('a', 'b', 'c')

for data in zip(list1, list2):
    print(type(data))
    print(f"{data[0]} -> {data[1]}")

print()

Different size
<class 'tuple'>
1 -> a
<class 'tuple'>
2 -> b
<class 'tuple'>
3 -> c

In [ ]:

keys = ["name", "age", "city"]
values = ["David", 28, "Tokyo"]

person_dict = dict(zip(keys, values))

print(person_dict)


matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("\nOriginal matrix:")
for row in matrix:
    print(row)

print("\nTransposed matrix:")
for column in zip(*matrix):
    print(column)

## 2.2 enumerate()  - gives you both the index and the value of each element

In [10]:
fruits = ["apple", "banana", "orange", "mango"]
print("\nBasic enumerate():")
for index, fruit in enumerate(fruits):
    print(f"Index {index}: {fruit}")

print("\nenumerate() with custom starting index:")

for index, fruit in enumerate(fruits[1:], start=1):
    print(f"{index}. {fruit}")

Basic enumerate():
Index 0: apple
Index 1: banana
Index 2: orange
Index 3: mango

enumerate() with custom starting index:
1. banana
2. orange
3. mango

## 2.3 BREAK - Exit the loop prematurely

In [7]:
numbers = [10, 20, 30, 40, 50]
for num in numbers:
    print(f"Checking {num}")
    if num == 30:
        print("Found 30! Breaking out of loop")
        break

print("Loop ended")

print("\nBreak in nested loops (breaks inner loop only):")

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for row in matrix:
    print(f"Row: {row}")
    for num in row:
        print(f"  Checking {num}")
        if num == 5:
            print("  Found 5! Breaking inner loop")
            break
    print("  Inner loop ended for this row")

Checking 10
Checking 20
Checking 30
Found 30! Breaking out of loop
Loop ended

Break in nested loops (breaks inner loop only):
Row: [1, 2, 3]
  Checking 1
  Checking 2
  Checking 3
  Inner loop ended for this row
Row: [4, 5, 6]
  Checking 4
  Checking 5
  Found 5! Breaking inner loop
  Inner loop ended for this row
Row: [7, 8, 9]
  Checking 7
  Checking 8
  Checking 9
  Inner loop ended for this row

# 2.4 CONTINUE - Skip to next iteration

In [8]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for num in numbers:
    if num % 2 == 0:
        continue  # Skip even numbers
    print(f"{num} is odd")


matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print("\nContinue in nested loops (breaks inner loop only):")
for row in matrix:
    print(f"Row: {row}")
    for num in row:
        if num % 2 == 0:
            continue  # Skip even numbers
        print(f"  Odd number: {num}")

1 is odd
3 is odd
5 is odd
7 is odd
9 is odd

Continue in nested loops (breaks inner loop only):
Row: [1, 2, 3]
  Odd number: 1
  Odd number: 3
Row: [4, 5, 6]
  Odd number: 5
Row: [7, 8, 9]
  Odd number: 7
  Odd number: 9

# 3. ITERTOOLS PACKAGE - Advanced iteration tools

In [ ]:

from itertools import (
    count, cycle, repeat,
    chain, combinations, permutations, product,
    accumulate
)
from more_itertools import chunked, distribute, divide


## 3.1 count() - creates an infinite counter

In [10]:

print("First 5 values starting from 0:")
counter = count()
for i in range(5):
    print(next(counter), end=" ")
print()


print("\ncount() with start and step:")
counter = count(start=10, step=2)
for i in range(5):
    print(next(counter), end=" ")
print()

First 5 values starting from 0:
0 1 2 3 4

count() with start and step:
10 12 14 16 18

## 3.2 cycle() - cycles through elements infinitely

In [11]:
print("\ncycle() - Repeats elements infinitely:")
cycler = cycle(['A', 'B', 'C'])
for i in range(8):
    print(next(cycler), end=" ")
print()

cycle() - Repeats elements infinitely:
A B C A B C A B


## 3.3  repeat() - repeats an element infinitely (or n times)

In [12]:
print("Repeating 'X' 5 times:")
repeater = repeat(['X', "r"], 5)
for item in repeater:
    print(item, end=" ")
print()

print("\nrepeating without limit (first 6):")
repeater = repeat(42)
for i in range(6):
    print(next(repeater), end=" ")
print()

Repeating 'X' 5 times:
['X', 'r'] ['X', 'r'] ['X', 'r'] ['X', 'r'] ['X', 'r']

repeating without limit (first 6):
42 42 42 42 42 42

## 3.4 combinations() - r-length tuples without replacement

In [13]:

elements = ['A', 'B', 'C', 'D']
print(f"2-combinations of {elements}:")
for combo in combinations(elements, 2):
    print(combo, end=" ")
print()

print(f"\n3-combinations of {elements}:")
for combo in combinations(elements, 3):
    print(combo, end=" ")
print()

2-combinations of ['A', 'B', 'C', 'D']:
('A', 'B') ('A', 'C') ('A', 'D') ('B', 'C') ('B', 'D') ('C', 'D')

3-combinations of ['A', 'B', 'C', 'D']:
('A', 'B', 'C') ('A', 'B', 'D') ('A', 'C', 'D') ('B', 'C', 'D')


## 3.5 permutations() - r-length tuples with all orderings

In [14]:

print("\npermutations() - All permutations (order matters):")
elements = ['A', 'B', 'C']
print(f"2-permutations of {elements}:")
for perm in permutations(elements, 2):
    print(perm, end=" ")
print()

print(f"\n3-permutations of {elements}:")
for perm in permutations(elements, 3):
    print(perm, end=" ")
print()

permutations() - All permutations (order matters):
2-permutations of ['A', 'B', 'C']:
('A', 'B') ('A', 'C') ('B', 'A') ('B', 'C') ('C', 'A') ('C', 'B')

3-permutations of ['A', 'B', 'C']:
('A', 'B', 'C') ('A', 'C', 'B') ('B', 'A', 'C') ('B', 'C', 'A') ('C', 'A', 'B') ('C', 'B', 'A')


## 3.6 product() - cartesian product

In [15]:

print("\nproduct() - Cartesian product:")
list1 = ['A', 'B']
list2 = [1, 2, 3]
print(f"product({list1}, {list2}):")
for item in product(list1, list2):
    print(item, end=" ")
print()

print("\nproduct() - Multiple repeat:")
print("product('AB', repeat=2) - All 2-length combinations with replacement:")
for item in product('AB', repeat=2):
    print(item, end=" ")
print()

product() - Cartesian product:
product(['A', 'B'], [1, 2, 3]):
('A', 1) ('A', 2) ('A', 3) ('B', 1) ('B', 2) ('B', 3)

product() - Multiple repeat:
product('AB', repeat=2) - All 2-length combinations with replacement:
('A', 'A') ('A', 'B') ('B', 'A') ('B', 'B')



## 3.7 chain() - chains multiple iterables together

In [16]:
print("\nchain() - Combine multiple iterables:")
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']
list3 = [10, 20]
print(f"Chaining {list1}, {list2}, {list3}:")
for item in chain(list1, list2, list3):
    print(item, end=" ")
print()



print("\nchain.from_iterable() - Flatten nested iterables:")
nested = [[1, 2, 3], [4, 5], [6, 7, 8]]
print(f"Flattening {nested}:")
for item in chain.from_iterable(nested):
    print(item, end=" ")
print()

chain() - Combine multiple iterables:
Chaining [1, 2, 3], ['a', 'b', 'c'], [10, 20]:
1 2 3 a b c 10 20

chain.from_iterable() - Flatten nested iterables:
Flattening [[1, 2, 3], [4, 5], [6, 7, 8]]:
1 2 3 4 5 6 7 8


## 3.8 accumulate() - running calculations

In [17]:

numbers = [1, 2, 3, 4, 5]
print(f"Cumulative sum of {numbers}:")
for result in accumulate(numbers):
    print(result, end=" ")
print()

print("\nCumulative product:")
for result in accumulate(numbers, lambda x, y: x * y):
    print(result, end=" ")
print()

Cumulative sum of [1, 2, 3, 4, 5]:
1 3 6 10 15

Cumulative product:
1 2 6 24 120

# 3.9 chunked() - Break iterable into lists of length n

In [18]:
list(chunked([1, 2, 3, 4, 5, 6, 7, 8], 3))

[[1, 2, 3], [4, 5, 6], [7, 8]]

##  3.10 distribute() - Distribute the items from iterable among n smaller iterables.

In [19]:
children = distribute(3, [1, 2, 3, 4, 5, 6, 7])
print([list(c) for c in children])

children = distribute(5, [1, 2, 3])
print([list(c) for c in children])

[[1, 4, 7], [2, 5], [3, 6]]
[[1], [2], [3], [], []]

## 3.11 divide() - Divide the elements from iterable into n parts, maintaining order.

In [20]:

children = divide(3, [1, 2, 3, 4, 5, 6, 7])
print([list(c) for c in children])

[[1, 2, 3], [4, 5], [6, 7]]

# 4 Function declaration and use

In [28]:
def my_addition(x, y = 5., **toto):
    print(f"{x} + {y} = {x + y}")
    if "z" in toto.keys():
        print(f"Additional parameter z: {toto['z']}")

In [27]:
my_addition(10, 15)
my_addition(x=4, y=3)
my_addition(3)

10 + 15 = 25
4 + 3 = 7
3 + 5.0 = 8.0

In [29]:
my_addition(x=4, y=3, z=7)  # This will raise a TypeError since 'z' is not a valid parameter

4 + 3 = 7
Additional parameter z: 7

In [14]:
parameters_list = [
    {
        "x": 10,
        "y": 15
    },
    {
        "x": 4,
    },
    {
        "y": 4
    }
]

for parameters in parameters_list:
    my_addition(**parameters)

10 + 15 = 25
4 + 5.0 = 9.0

TypeError: my_addition() missing 1 required positional argument: 'x'

# 5. Use built-in method

In [ ]:
import numpy as np 
import polars as pl


sample = pl.DataFrame({
    "sample":np.random.normal(loc=0.0, scale=50.0, size=1_000_000)
})
sample

shape: (1_000_000, 1)
┌────────────┐
│ sample     │
│ ---        │
│ f64        │
╞════════════╡
│ -27.798627 │
│ 50.630466  │
│ -28.396549 │
│ 25.822486  │
│ 23.734809  │
│ …          │
│ -35.886363 │
│ -0.956349  │
│ -44.474755 │
│ -13.781583 │
│ 12.261678  │
└────────────┘

In [ ]:

sample = sample.with_columns(
    pl.col("sample").cut(breaks=[-50.0, -25.0, 25.0, 50.0], labels=["very low", "low", "medium", "high", "very high"])
    .alias("category")
).with_columns(
    (pl.col("sample") / pl.col("sample").mean().over("category")).alias("normalized")
)

sample

shape: (1_000_000, 3)
┌────────────┬───────────┬──────────────┐
│ sample     ┆ category  ┆ normalized   │
│ ---        ┆ ---       ┆ ---          │
│ f64        ┆ enum      ┆ f64          │
╞════════════╪═══════════╪══════════════╡
│ -27.798627 ┆ low       ┆ 0.757773     │
│ 50.630466  ┆ very high ┆ 0.663816     │
│ -28.396549 ┆ low       ┆ 0.774072     │
│ 25.822486  ┆ high      ┆ 0.702901     │
│ 23.734809  ┆ medium    ┆ -1884.699022 │
│ …          ┆ …         ┆ …            │
│ -35.886363 ┆ low       ┆ 0.97824      │
│ -0.956349  ┆ medium    ┆ 75.940363    │
│ -44.474755 ┆ low       ┆ 1.212354     │
│ -13.781583 ┆ medium    ┆ 1094.347774  │
│ 12.261678  ┆ medium    ┆ -973.657438  │
└────────────┴───────────┴──────────────┘

In [ ]:
sample.group_by("category").agg(
    pl.len().alias("count"),
    pl.col("sample").mean().alias("mean"),
    pl.col("sample").std().alias("std"),
    pl.col("normalized").mean().alias("normalized_mean"),
    pl.col("normalized").std().alias("normalized_std")
)

shape: (5, 6)
┌───────────┬────────┬────────────┬───────────┬─────────────────┬────────────────┐
│ category  ┆ count  ┆ mean       ┆ std       ┆ normalized_mean ┆ normalized_std │
│ ---       ┆ ---    ┆ ---        ┆ ---       ┆ ---             ┆ ---            │
│ enum      ┆ u32    ┆ f64        ┆ f64       ┆ f64             ┆ f64            │
╞═══════════╪════════╪════════════╪═══════════╪═════════════════╪════════════════╡
│ very low  ┆ 158389 ┆ -76.208218 ┆ 22.193127 ┆ 1.0             ┆ 0.291217       │
│ high      ┆ 150017 ┆ 36.717032  ┆ 7.165147  ┆ 1.0             ┆ 0.195145       │
│ low       ┆ 149910 ┆ -36.689294 ┆ 7.152431  ┆ 1.0             ┆ 0.194946       │
│ very high ┆ 158758 ┆ 76.316971  ┆ 22.321617 ┆ 1.0             ┆ 0.292486       │
│ medium    ┆ 382926 ┆ 0.045167   ┆ 14.211085 ┆ 1.0             ┆ 314.632519     │
└───────────┴────────┴────────────┴───────────┴─────────────────┴────────────────┘

In [17]:
from data_config import DataConfig

In [18]:
data_config = DataConfig()

In [21]:
data_config.__dict__

{'hub_current_default': 0.0,
 'hub_power_default': 0.0,
 'ss_voltage_default': 750,
 'r_dc_default': 0.13,
 'r_dc_feeder_default': 0.002,
 'r_ss_default': 0,
 'r_hub_default': 0.001,
 'step_length': 1,
 'unladen_weight': 10000.0,
 'max_load_weight': 1000.0,
 'rotational_inertia_ratio': 0.1,
 'max_speed': 10,
 'max_acceleration': 1.0,
 'auxiliary_consumption': 20000.0,
 'traction_efficiency': 0.95,
 'injection_efficiency': 0.7,
 'gravity_acceleration': 9.81,
 'coef_curve_1': 0.65,
 'coef_curve_2': 15.0,
 'coef_friction_1': 1.59,
 'coef_friction_2': 0.0248,
 'coef_friction_3': 0.0137,
 'coef_friction_4': 0.0,
 'coef_friction_5': 0.0,
 'coef_friction_6': 0.0,
 'tol': 0.001,
 'max_iter': 3000,
 'dc_timestep': datetime.timedelta(seconds=1),
 'ac_timestep': datetime.timedelta(seconds=900),
 'simulation_date': datetime.date(2025, 1, 1),
 'start_simulation_time': None,
 'end_simulation_time': None,
 'position_precision': 1,
 'nb_points_per_meter': 25,
 'ss_voltage_update_factor': 25,
 'train_power_update_factor': 5,
 'fix_update_period': 5,
 'plotting_path': '.cache/plotting',
 'nb_timestep_per_sim': 900}